### ISSUE TITLE
a11y: When search list is open, using the arrow keys should navigate through the list

### ISSUE THREAD

**Issue by TimvdLippe** [webcomponents/webcomponents.org#684] opened 2016-11-30 11:34 UTC
When I have search results and the focus is in the input, when I press the arrow key down I want to select the first search item. Consequently up and down should move the focus through the items of the list accordingly or back up to the search input

**Comment by bkjohnson** [comment] 2017-04-19 01:34
This is a dupe of the third list item in #470 right?

**Comment by samuelli** [comment] 2017-04-19 01:36
Yup! Added an extra item to #470 too.

**Closed by samuelli** 2017-04-19 01:36 UTC
Labels: Help wanted
