### ISSUE TITLE
Searchbar is borked in Shadow DOM

### ISSUE THREAD

**Issue by e111077** [webcomponents/webcomponents.org#939] opened 2017-04-19 00:01 UTC
When appending `?dom=shadow` to the URL the searchbar seems to act oddly. See screenshot:

![image](https://cloud.githubusercontent.com/assets/5981958/25157828/9e3781b6-2458-11e7-9431-b680ce48150e.png)

**Comment by samuelli** [comment] 2017-04-19 01:37
Lots of fun things are broken in shadow DOM, but we should aim to be pretty close to fully working.

**Comment by Link2Twenty** [comment] 2018-01-05 13:17
I think the problem is [catalog-search-box#L152](https://github.com/webcomponents/webcomponents.org/blob/ae6f3addb0ceed898f1939f7080ac194e91faac7/client/src/catalog-search-box.html#L152)

Looking at the [documentation](https://www.polymer-project.org/2.0/docs/devguide/style-shadow-dom#use-css-selectors-to-style-the-host-element) the code should be something like

```
:host(:not(.expanded)) > #results {
  display: none;
}
```

With just extra brackets around the `:not`

**Comment by samuelli** [comment] 2018-01-16 19:27
Still broken based on the repro steps

**Comment by Link2Twenty** [comment] 2018-01-16 22:01
Looking at the source it doesn't look like it's picked up the new code, also I didn't get the usual site updated toast.

**Comment by samuelli** [comment] 2018-01-17 00:22
Sorry, the site hasn't been updated yet. Waiting on that last PR to get merged, but Travis appears to be down.

**Comment by samuelli** [comment] 2018-01-17 22:41
This has been updated now.

**Comment by Link2Twenty** [comment] 2018-01-17 22:52
I'm on mobile but it looks ok from here.

**Comment by Link2Twenty** [comment] 2018-01-19 22:05
Ok, the initial problem has been solved but a new one has appeared.

![search-zero](https://user-images.githubusercontent.com/3534427/35173399-40a31436-fd63-11e7-8b03-f00a7c84efe7.png)

The `collections` header still appears even though it has zero results. The hidden attribute is getting applied but is being overwritten by `display: flex` ([catalog-search-box.html#L86](https://github.com/webcomponents/webcomponents.org/blob/master/client/src/catalog-search-box.html#L86))

A simple solution would be to add hidden as a selector within the element or `catalog-styles`.
```CSS
[hidden] {
  display:none;
}
```

**Comment by Link2Twenty** [comment] 2018-01-23 16:58
When setting display in `:host` there should also be a `:host([hidden])` rule, I'll do a pull request this week.

https://developers.google.com/web/fundamentals/web-components/best-practices#add-a-host-display-style-that-respects-the-hidden-attribute

**Closed** 2018-02-13 14:30 UTC
Labels: Help wanted
