### ISSUE TITLE
Analysis fails

### ISSUE THREAD

**Issue by nomego** [webcomponents/webcomponents.org#1042] opened 2017-07-26 10:49 UTC
[Origin page](https://www.webcomponents.org/preview/Neovici/cosmoz-autocomplete/7e477a949b404855055c5771dc719411be304bf8)

https://www.webcomponents.org/api/docs/Neovici/cosmoz-autocomplete/7e477a949b404855055c5771dc719411be304bf8?use_analyzer_data gives 

```json
{"status": "error", "error": "true"}
```

Why?

**Comment by samuelli** [comment] 2017-07-26 18:57
Looks like bower install fails to install without any prompts. You can reproduce this locally by running
```bash
bower install Neovici/cosmoz-autocomplete
```

**Comment by nomego** [comment] 2017-07-26 19:25
Oh ok, thanks, will look into it.
It would be good if this would be mentioned somewhere in the guide to publishing, or did I miss it?
Or in the error response of that call.

**Comment by nomego** [comment] 2017-08-05 06:57
How about this one ?

https://www.webcomponents.org/preview/arpit2438735/cosmoz-bottom-bar/ea2048492d11c4ad43358ecee9b51f438c6cf6a0

**Comment by samuelli** [comment] 2017-08-07 22:12
Try:
```
bower install arpit2438735/cosmoz-bottom-bar#ea2048492d11c4ad43358ecee9b51f438c6cf6a0
```

on a clean directory.

**Comment by nomego** [comment] 2017-08-08 07:42
Works fine.
There seems to be an issue when previewing PRs, since master works fine and this is a simple PR that shouldn't break anything.
See https://github.com/Neovici/cosmoz-bottom-bar/pull/12

**Comment by samuelli** [comment] 2017-09-08 23:52
Sorry for not getting back to you. I think we have a limitation currently on previewing pull requests that aren't in the actual repo. In this case, the system resolves to a merge commit, which you can't actually bower install. Instead it would actually need to point to a different repo.

I'm closing this issue, please open an issue if ^ is affecting your flow considerably, but at this stage I don't really have the bandwidth to fix this particular use-case.

**Closed by samuelli** 2017-09-08 23:52 UTC
