### ISSUE TITLE
Front page carousels don't scroll with momentum on iOS

### ISSUE THREAD

**Issue by tjsavage** [webcomponents/webcomponents.org#831] opened 2017-01-25 03:01 UTC
Chrome on Android, the carousels have a nice fling momentum. They don't on iOS.

Perhaps tangentially related to https://github.com/webcomponents/webcomponents.org/issues/781

**Comment by samuelli** [comment] 2017-01-25 05:09
Dupe of #778.

**Closed by samuelli** 2017-01-25 05:09 UTC
