### ISSUE TITLE
www.webcomponents.org always returns gzip'd content 

### ISSUE THREAD

**Issue by ithinkihaveacat** [webcomponents/webcomponents.org#793] opened 2017-01-11 17:48 UTC
The `www.webcomponents.org` server appears to always return gzip'd content, even if the client didn't ask for it:

```sh
# actual
$ curl -sH 'accept-encoding:' https://www.webcomponents.org/manifest.json | gzip -d
{
    "name": "Web Components",
    "short_name": "wc.org",
    "icons": [
        {
...
# expected
$ curl -sH 'accept-encoding:' https://www.webcomponents.org/manifest.json | gzip -d
gzip: unknown compression format
```

(The `Accept-Encoding` header of the response is also set to `gzip`.)

This seems to be confusing various tools such as `https://manifest-validator.appspot.com/` that are requesting `https://www.webcomponents.org/manifest.json` and getting unintelligible `gzip` responses back:

![manifest-validator appspot com- nexus 5x](https://cloud.githubusercontent.com/assets/51244/21859767/df46b5d4-d825-11e6-9fed-5f704dadeec5.png)

**Comment by samuelli** [comment] 2017-01-19 00:37
Thanks for the report @ithinkihaveacat.

Is this still reproducing? I was unable to reproduce the results. May have been an unrelated app engine change that affected us. I'm going to close this for now, let me know if its still reproducing or pops up again!

```
$ curl -sH 'accept-encoding:' https://www.webcomponents.org/manifest.json | gzip -d
gzip: stdin: not in gzip format
```
![image](https://cloud.githubusercontent.com/assets/787668/22088888/70ae792e-de3b-11e6-9e23-ee9424f75556.png)

**Comment by adewale** [comment] 2017-01-19 00:48
I have just tested this from my home network and reproduced it.

curl -sH 'accept-encoding:' https://www.webcomponents.org/manifest.json | gzip -d
{
    "name": "Web Components",
    "short_name": "wc.org",
    "icons": [
        {
            "src": "\/assets\/android-chrome-192x192.png",
            "sizes": "192x192",
            "type": "image\/png"
        },
        {
            "src": "\/assets\/android-chrome-512x512.png",
            "sizes": "512x512",
            "type": "image\/png"
        }
    ],
    "start_url": "/",
    "background_color": "#ffffff",
    "theme_color": "#ffffff",
    "display": "standalone"

**Comment by samuelli** [comment] 2017-01-19 01:46
Hmm, we serve this a static file using app engines infrastructure, so there's not much we can do here if there is an issue.

@ithinkihaveacat: with the manifest validator site, you need to enter `https://www.webcomponents.org` not `https://www.webcomponents.org/manifest.json` for it to work.

**Closed by samuelli** 2017-01-19 01:46 UTC

**Comment by ithinkihaveacat** [comment] 2017-01-19 06:27
It works for me now too. (Have added it to `https://pwa-directory.appspot.com/pwas/add`.) Maybe GAE was doing something weird.

**Comment by ithinkihaveacat** [comment] 2017-01-19 06:27
Thanks!
