### ISSUE TITLE
SSL certificate chain is incomplete

### ISSUE THREAD

**Issue by agross** [webcomponents/webcomponents.org#807] opened 2017-01-17 18:43 UTC
[Origin page](https://www.webcomponents.org/)

See: https://www.ssllabs.com/ssltest/analyze.html?d=www.webcomponents.org

This might cause errors when trying to browse webcomponents.org.

**Comment by samuelli** [comment] 2017-01-17 22:25
Thanks for the report @agross. Looks like this might be the cause of #804 too. I'll take a look.

**Comment by dstockwell** [comment] 2017-01-18 02:43
This should be fixed now.

**Closed by dstockwell** 2017-01-18 02:43 UTC
